version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"

    steps:
      - checkout
      - run: go mod download
      - run: go build
      # - run: go test -v ./...
